# Autogenerated file
onerror {
	quit -f -code 1
}
vmap -c
if [file exists sim_build/work] {vdel -lib sim_build/work -all}
vlib sim_build/work
vmap work sim_build/work
vlog -work work +define+COCOTB_SIM -sv -timescale 1ns/1ps -mfcu +acc  ../src/mod_add.v ../src/mod_inv.v ../src/mod_mul.v ../src/mod_sub.v ../src/point_add.v ../src/scalar_mul.v
vsim  -onfinish exit -pli /u/satyajit/.local/lib/python3.6/site-packages/cocotb/libs/libcocotbvpi_modelsim.so   work.scalar_mul
onbreak resume
run -all
quit
